using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using System.Collections.Generic;
using Xunit;
using SqlAudit.Core.Models;

namespace SqlAudit.Tests;

public class ProgramTests
{
    [Fact]
    public void TryLoadSnapshot_InvalidJson_CatchesExceptionAndReturnsNull()
    {
        // Arrange
        var tempFile = Path.GetTempFileName();
        try
        {
            File.WriteAllText(tempFile, "invalid json");

            var assembly = typeof(SqlAudit.Cli.CliOptions).Assembly;
            var programType = assembly.GetType("Program");
            Assert.NotNull(programType);

            // Find the method ignoring generic names generated by compiler
            var tryLoadSnapshotMethod = programType.GetMethods(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Static)
                .FirstOrDefault(m => m.Name.Contains("TryLoadSnapshot"));

            Assert.NotNull(tryLoadSnapshotMethod);

            // Redirect standard error
            var originalError = Console.Error;
            using var sw = new StringWriter();
            Console.SetError(sw);

            try
            {
                // Act
                var result = tryLoadSnapshotMethod.Invoke(null, new object[] { tempFile });

                // Assert
                Assert.Null(result);
                var errorOutput = sw.ToString();
                Assert.Contains("Warning: Failed to load previous snapshot from", errorOutput, StringComparison.Ordinal);
                Assert.Contains("Details:", errorOutput, StringComparison.Ordinal);
            }
            finally
            {
                Console.SetError(originalError);
            }
        }
        finally
        {
            if (File.Exists(tempFile))
            {
                File.Delete(tempFile);
            }
        }
    }

    [Fact]
    public void TryLoadSnapshot_FileDoesNotExist_ReturnsNull()
    {
        // Arrange
        var nonExistentFile = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString() + ".json");

        var assembly = typeof(SqlAudit.Cli.CliOptions).Assembly;
        var programType = assembly.GetType("Program");
        Assert.NotNull(programType);

        var tryLoadSnapshotMethod = programType.GetMethods(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Static)
            .FirstOrDefault(m => m.Name.Contains("TryLoadSnapshot"));

        Assert.NotNull(tryLoadSnapshotMethod);

        // Act
        var result = tryLoadSnapshotMethod.Invoke(null, new object[] { nonExistentFile });

        // Assert
        Assert.Null(result);
    }
}
